name: Main Workflow
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install Dependency
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
      - name: Unit Test
        run: |
          python manage.py makemigrations
          python manage.py migrate
          python manage.py collectstatic
          python manage.py test catalog
      - name: Coverage Run
        run: |
          coverage run --include="./*" --omit="manage.py,locallibrary/*,venv/*" manage.py test catalog register
          coverage report -m
          coverage xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          file: ./coverage.xml
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
