name: CI Pipelines
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install Dependency
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
      - name: Unit Test
        run: |
          python manage.py makemigrations
          python manage.py migrate
          python manage.py collectstatic
          python manage.py test catalog
      - uses: codecov/codecov-action@v1
